# Generated by Django 4.2.1 on 2023-10-27 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBModelBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestRecord',
            fields=[
                ('dbmodelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data_viewer.dbmodelbase')),
                ('event', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('path', models.CharField(max_length=100)),
                ('params', models.CharField(max_length=100)),
                ('status_code', models.IntegerField()),
            ],
            bases=('data_viewer.dbmodelbase',),
        ),
    ]
