# Generated by Django 4.2.1 on 2023-10-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestRecord',
            new_name='Transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='event',
            new_name='method',
        ),
    ]
